// src/lib/sources/companies.ts
import { ATSConfig, JobMode } from "@/types";

export interface CompanyConfig extends ATSConfig {
  pipelines: JobMode[];
}

const COUNTRY_EGY = "Egypt";
const FLAG_EGY = "🇪🇬";

export const ALL_COMPANIES: CompanyConfig[] = [
  // ── LOCAL PIPELINE (Egypt Based) ─────────────────────────────────────────
  {
    ats: "lever",
    name: "Bosta",
    slug: "Bosta",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "ashby",
    name: "Thndr",
    slug: "thndr",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "ashby",
    name: "MoneyHash",
    slug: "moneyhash",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Yassir",
    slug: "YassirGmbh",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Algoriza",
    slug: "Algoriza",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Khazna Tech",
    slug: "khaznatech",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "valU",
    slug: "valu",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Homzmart",
    slug: "Homzmart",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Brimore",
    slug: "Brimore",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "smartrecruiters",
    name: "Flextock",
    slug: "Flextock",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Swvl",
    slug: "swvl",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Klivvr",
    slug: "klivvr",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Nawy",
    slug: "nawy-real-estate",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Dubizzle",
    slug: "bayutdubizzle",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Rubikal",
    slug: "rubikal",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Blink22",
    slug: "blink22-3",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Squadio",
    slug: "squadio23",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Robusta",
    slug: "robusta",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Moneyfellows",
    slug: "moneyfellows",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Sideup",
    slug: "sideup",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Cartona",
    slug: "global-ventures",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Taager",
    slug: "taager",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "NearPay",
    slug: "nearpay",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Lean Technologies",
    slug: "leantech",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Atomica",
    slug: "atomica",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Advansys",
    slug: "advansys",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Sumerge",
    slug: "sumerge",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Integrant",
    slug: "integrant",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Eva Pharma",
    slug: "eva-pharma",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "SWATX",
    slug: "swatx",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "ArpuPlus",
    slug: "arpu-telecommunication-services",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "workable",
    name: "Sary",
    slug: "sary",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "bamboohr",
    name: "Instabug",
    slug: "instabug",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },
  {
    ats: "breezy",
    name: "MaxAB",
    slug: "maxab",
    country: COUNTRY_EGY,
    countryFlag: FLAG_EGY,
    city: "Cairo",
    pipelines: ["local"],
  },

  // ── VISA PIPELINE (Relocation Hubs) ──────────────────────────────────────
  {
    ats: "greenhouse",
    name: "Contentful",
    slug: "contentful",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "N26",
    slug: "n26",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "SumUp",
    slug: "sumup",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Babbel",
    slug: "babbel",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Adyen",
    slug: "adyen",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Elastic",
    slug: "elastic",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Monzo",
    slug: "monzo",
    country: "UK",
    countryFlag: "🇬🇧",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Intercom",
    slug: "intercom",
    country: "Ireland",
    countryFlag: "🇮🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Wallapop",
    slug: "wallapop",
    country: "Spain",
    countryFlag: "🇪🇸",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Pleo",
    slug: "pleo",
    country: "Denmark",
    countryFlag: "🇩🇰",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Wolt",
    slug: "wolt",
    country: "Finland",
    countryFlag: "🇫🇮",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Doctolib",
    slug: "doctolib",
    country: "France",
    countryFlag: "🇫🇷",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Zenjob",
    slug: "zenjob",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Solarisbank",
    slug: "solarisbank",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "GoCardless",
    slug: "gocardless",
    country: "UK",
    countryFlag: "🇬🇧",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Catawiki",
    slug: "catawiki",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Scandit",
    slug: "scandit",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Feedzai",
    slug: "feedzai",
    country: "Portugal",
    countryFlag: "🇵🇹",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Squarespace",
    slug: "squarespace",
    country: "Ireland",
    countryFlag: "🇮🇪",
    pipelines: ["visa"],
  },
  {
    ats: "ashby",
    name: "Mollie",
    slug: "mollie",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Raisin",
    slug: "raisin",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "greenhouse",
    name: "Backbase",
    slug: "backbase",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    pipelines: ["visa"],
  },
  {
    ats: "ashby",
    name: "DeepL",
    slug: "deepl",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "smartrecruiters",
    name: "Enpal",
    slug: "EnpalBV",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },
  {
    ats: "workable",
    name: "Plan A",
    slug: "plana",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["visa"],
  },

  // ── GLOBAL PIPELINE (Remote Worldwide) ───────────────────────────────────
  {
    ats: "greenhouse",
    name: "Webflow",
    slug: "webflow",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Mercury",
    slug: "mercury",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Vercel",
    slug: "vercel",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Airbnb",
    slug: "airbnb",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Discord",
    slug: "discord",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Coinbase",
    slug: "coinbase",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Figma",
    slug: "figma",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Grafana",
    slug: "grafanalabs",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Netlify",
    slug: "netlify",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Lyft",
    slug: "lyft",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Reddit",
    slug: "reddit",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Pinterest",
    slug: "pinterest",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Databricks",
    slug: "databricks",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Twilio",
    slug: "twilio",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Okta",
    slug: "okta",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Cloudflare",
    slug: "cloudflare",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "DataDog",
    slug: "datadog",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Asana",
    slug: "asana",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Checkr",
    slug: "checkr",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Gusto",
    slug: "gusto",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Moonfare",
    slug: "moonfare",
    country: "Germany",
    countryFlag: "🇩🇪",
    pipelines: ["global"],
  },
  {
    ats: "greenhouse",
    name: "Stripe",
    slug: "stripe",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global", "visa"],
  },
  {
    ats: "ashby",
    name: "Posthog",
    slug: "posthog",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Infisical",
    slug: "infisical",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Resend",
    slug: "resend",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Stytch",
    slug: "stytch",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Raycast",
    slug: "raycast",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Supabase",
    slug: "supabase",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Neon",
    slug: "neon",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Plain",
    slug: "plain",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Linear",
    slug: "linear",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Airbyte",
    slug: "airbyte",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "ashby",
    name: "Rasa",
    slug: "rasa",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global", "visa"],
  },
  {
    ats: "workable",
    name: "Learnworlds",
    slug: "learnworlds",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
  {
    ats: "workable",
    name: "Clerk",
    slug: "clerk",
    country: "Global",
    countryFlag: "🌍",
    pipelines: ["global"],
  },
];
